version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      cNJoW5LdMfzyHf+OhyT1wIxdSPo26tYOoHAu6+l3henK3OUveEdKmWSe29lL4DvvyuAogvPt60hz6/2Kb8PuUXa2gb+pGmutQCI/vrvJvW/PLvs1kUT/EEwzNHHCg29E81/bv/nZO5OzxlHPwZbP7ZQ34OiK29w4ZcJu+v+Vj6U=
