# v1.3.8 November 7, 2013
# https://github.com/bevry/base
sudo: false
language: node_js
before_install: "npm install -g npm"
install: "npm install; ./node_modules/.bin/cake install"
before_script: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.8"
  - "0.10"
notifications:
  irc:
    - "irc.freenode.org#bevry-dev"
  email:
    recipients:
      - travisci@bevry.me
